### list users
GET http://localhost:3000/users

### get user
GET http://localhost:3000/users/66a3d7efdcdbec92d28eeba

### create user
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Joao Alberto",
    "email":"juliamatos@test.com",
    "password": "test1234"
}

### update user
PATCH http://localhost:3000/users/66a3d7efdcdbec92d28eeba
Content-Type: application/json

{
    "name": "Joao Felipe"
}

### delete user
DELETE http://localhost:3000/users/66a2c2dc135e3562ac58078
